### ISSUE TITLE
Better Doc + Containers? 

### ISSUE THREAD

**Issue by jkakkar** [openthc/pos#2]
Hi Team,

I was having issues compiling and deploying this following docs. took a lot of time to find all the dependencies by going through the other repo's you had.

can we make this more clear in deploying? Also, have you thought about containerizing this?

-J

**Comment by rickconlee** [comment]
I'm looking into this - i know this is old, but do you remember what kind of issues you were having when you were trying to deploy this?

**Comment by endlessblends** [comment]
Is there anymore documentation available? I can gather what the stack is, but it's not specifically stated anywhere. Also, DB tables are in another repo somewhere? Is that repo required to run the POS? Is the whole Openthc set of apps required in order to run the POS? Thanks for making what looks to be a great opensource set of tools for the industry! If it weren't lacking in documentation I'd consider using it live in stores.

**Comment by djbusby** [comment]
We've not had much time to dedicate to the docs section.  The repo called CRE has database-schema defined in SQL files -- so that schema is added to new DB or in some cases modded-into existing DB infrastructure.  POS runs with just it's code -- to provide the front-end features.  The back-end data is generally handled by other tools (assuming you're integrated with some regulatory system like METRC).  Other tools in our github (eg: pipe, bong) are complementatry but not strictly necessary - in some cases they used as references for a companies existing custom tooling. 

And, of course, contributions are always welcome to help improve the documentation!

**Comment by endlessblends** [comment]
Hi djbusby. Thanks for providing some more insight on setting it up.  If I can figure out the structure, get it working, etc, I might use it in a few live dispensaries. Would love to contribute to the documentation if I can get this up and running. Thanks again for creating an open source option for the industry! I love the idea of a standardized API. Much appreciated. Time do dig in further and see if I can understand it a bit better.  Have an awesome day!

**Comment by ugintl** [comment]
@jkakkar Would you like to share the installation steps?

**Comment by mashiox** [comment]
See our docker project for container images and a reference install. https://github.com/openthc/docker
